### ISSUE TITLE
Remover console.log

### ISSUE THREAD

**Issue by Tamicktom** [Tamicktom/hammertail#29]
console.log só devem existir em ambientes de desenvolvimento. Deixe apenas warn e error para ambientes de produção.

Por exemplo, na página de Worlds:
![image](https://user-images.githubusercontent.com/60244227/232662162-5c519ba2-0b39-4bad-a50a-d1d439fc9cbf.png)

**Comment by viicruz** [comment]
Feito

**Comment by Tamicktom** [comment]
@viicruz coloca no apendice qual foi o commit que resolveu o problema, por favor. :3
