### ISSUE TITLE
Fix code scanning alert - Server-side request forgery

### ISSUE THREAD

**Issue by Tamicktom** [Tamicktom/hammertail#39]
Tracking issue for:
- [ ] https://github.com/Tamicktom/hammertail/security/code-scanning/1

**Comment by Tamicktom** [comment]
@viicruz isso aqui é muito, MUITO critico. Temos que corrigir o mais rápido possível.

**Comment by viicruz** [comment]
@Tamicktom Joga no peito do pai que o pai resolve

**Comment by Tamicktom** [comment]
Já foi resolvido. Vai ser adicionado na próxima iteração.
